language: node_js
node_js:
  - "stable"

before_install:
  - wget http://ftp.gnu.org/gnu/libc/glibc-2.27.tar.gz
  - tar zxvf glibc-2.27.tar.gz
  - cd glibc-2.27
  - mkdir build
  - cd build
  - ../configure --prefix=/usr
  - make
  - sudo make install

install:
  - npm install

script:
  - npm test
